# Generated by Django 3.2.18 on 2023-04-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_auto_20230420_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_task', models.TextField(verbose_name='Задача')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('author_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_tasks', to='employee.employee', verbose_name='Задание выдал')),
                ('for_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Выпоняет')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
